Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.ssh.insert_key = false
    config.vm.network "public_network", use_dhcp_assigned_default_route: true
    config.vm.provider :virtualbox do |mem|
        mem.memory = 8192 
    end
    config.vm.define 'centos' do |node|
        node.vm.hostname = 'centos.local'
        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "main.yml"
        end
    end
end
